version: '3.7'
services:
    db:
        image: mysql:5
        container_name: dockertest_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: example

    php:
        build: ./docker/php
        container_name: dockertest_php
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        links:
            - db

    nginx:
        image: nginx:latest 
        container_name: dockertest_ngnix
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/app
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./docker/nginx/logs:/var/log/nginx
        links:
            - php

    node:
        image: node:12.3-alpine
        container_name: dockertest_node
        ports:
          - "3000:3000"
        command: yarn run watch
        working_dir: /var/www/app
        environment:
            NODE_ENV: development
        volumes:
            - ./app:/var/www/app
            - /app/node_modules