export MYSQL_USER=$MYSQL_USER
export MYSQL_PASSWORD=$MYSQL_PASSWORD
export MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
export NODE_ENV=production
export APP_SECRET=$APP_SECRET
export MAILER_PASSWORD=$MAILER_PASSWORD
