version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "12:3a:30:37:95:2f:fa:47:d0:2d:2c:c4:e5:e9:89:2c"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/competition
            docker-compose down
            git reset --hard origin/master
            git pull origin master
            export MYSQL_USER=$MYSQL_USER
            export MYSQL_PASSWORD=$MYSQL_PASSWORD
            export MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            export NODE_ENV=production
            export APP_SECRET=$APP_SECRET
            export MAILER_PASSWORD=$MAILER_PASSWORD
            envsubst '${MYSQL_USER},${MYSQL_PASSWORD},${MYSQL_ROOT_PASSWORD},${NODE_ENV},${APP_SECRET},${MAILER_PASSWORD}' < .env > .env.tmp
            cp .env.tmp .env && rm .env.tmp
            docker-compose up -d
            sleep 10
            docker exec bzstu_php composer dump-env prod
            docker exec bzstu_php php bin/console doctrine:migrations:migrate --no-interaction
            "
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
