version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "12:3a:30:37:95:2f:fa:47:d0:2d:2c:c4:e5:e9:89:2c"
      - run:
          name: Deploy Over SSH
          command: |
            echo MYSQL_USER=$MYSQL_USER >> sshenv
            echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> sshenv
            echo MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD >> sshenv
            echo NODE_ENV=production >> sshenv
            echo APP_SECRET=$APP_SECRET >> sshenv
            echo MAILER_PASSWORD=$MAILER_PASSWORD >> sshenv

            scp sshenv $SSH_USER@$SSH_HOST:~/.ssh/environment
            envsubst < environments.sh | ssh $SSH_USER@$SSH_HOST "cd /home/competition
            docker-compose down
            git reset --hard origin/master
            git pull origin master
            export $(grep -v '^#' ~/.ssh/environment | xargs)
            envsubst < .env | > .env.tmp
            cat .env.tmp
            docker-compose up -d
            sleep 10
            docker exec bzstu_php composer dump-env prod
            docker exec bzstu_php php bin/console doctrine:migrations:migrate --no-interaction
            "
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
